apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: dilek-kumbarasi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJRWGxoZG5WNlpYSTZaMmh3WDNObGEwRkRZa1I1VVZWT2FIVjFka0V3TTJSNlJWcDFNV1ZVVkdNM2NqQkxXVU0zUlE9PSJ9fX0=
